# Site settings
name: ğ”¼ğ••ğ•£ğ•šğ•¤ ğ”»ğ•’ğ•Ÿğ•–ğ•¤ğ•™
description: "ğ‹ğšğ§ğ ğšğ«ğ®ğğŸ“<br />ğŸğŸğŸğŸ ğ‰ğ®ğ¥ğ² ğŸğŸ’âœ¨<br />ğ€ğ©ğ©ğ¥ğ¢ğğ ğ¦ğšğ­ğ¡ğğ¦ğšğ­ğ¢ğœğ¬ (á´œÉ´Éª á´Ò“ á´›á´€Ê™Ê€Éªá´¢)ğŸ‘¨ğŸ»â€ğŸ“<br />ğ†ğ®ğ¢ğ­ğšğ« ğŸ¸<br />â€œğ‘° ğ’ğ’ğ’—ğ’† ğ‘¯ğ’–ğ’ğ’‚ğ’ğ’Šğ’•ğ’š ğ’ƒğ’–ğ’• ğ‘° ğ’‰ğ’‚ğ’•ğ’† ğ’‰ğ’–ğ’ğ’‚ğ’ğ’”â€â€• ğ‘¨ğ’ğ’ƒğ’†ğ’“ğ’• ğ‘¬ğ’Šğ’ğ’”ğ’•ğ’†ğ’Šğ’ğŸ¥€<br />(xÂ²+yÂ²-1)Â³ - xÂ²yÂ³ = 0ğŸ–¤"
url: ""


# Delete the lines you don't need
# about 5 elements are recomended
github_username: edrianesh
linkedin_username: edris-danesh
facebook_username: edrianesh
instagram_username: edrianesh
twitter_username: edrianesh
whatsapp_username: 9331457011?text=Joon%Del%?
telegram_username: edrianesh
google_plus_username: edris.danesh2013@gmail.com
yahoo_username: edris.salamat@yahoo.com

avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "https://avatars.githubusercontent.com/u/108469602?v=4"


front_img: yes
front_img_path: "imgs/background.gif"
#front_img_path: "https://external.url/image.jpg"


favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty

